[package]
name = "v8_hts"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "v8_hts"


[dependencies]
rust-htslib = { version = "0.47.0", features = ["libdeflate", "static"] }
rusty_v8 = "0.32.1"
